rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Audio_Speaker\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Audio_Speaker\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID_MSC\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Device_Firmware_Upgrade\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\JoyStickMouse\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\JoyStickMouse\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Mass_Storage\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Mass_Storage\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Virtual_COM_Port\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\VirtualComport_Loopback\EWARM\STM32373C-EVAL

rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\MDK-ARM\STM32373C-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM32L152-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM32L152D-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM3210B-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM3210E-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM32303C-EVAL
rd  /s/q  .\Projects\Custom_HID_VCP\EWARM\STM32373C-EVAL
del *.bak /s
del *.ddk /s
del *.edk /s
del *.lst /s
del *.lnp /s
del *.mpf /s
del *.mpj /s
del *.obj /s
del *.omf /s
::del *.opt /s  ::������ɾ��JLINK������
del *.plg /s
del *.rpt /s
del *.tmp /s
del *.__i /s
del *._ip /s
del *._ia /s
del *.i /s
del *.crf /s
del *.o /s
del *.d /s
del *.axf /s
del *.tra /s
del *.dep /s           
del *.pbi /s
del *.xcl /s
del *.pbd /s
del *.linf /s
del *.browse /s
del *.crun /s
del *.dbgdt /s
del *.dnx /s
del *.ps1 /s
del *.wsdt /s
del JLinkLog.txt /s

del *.iex /s
del *.htm /s
::del *.sct /s
del *.map /s
del *.htm /s
del *.txt /s
del Projects/*.bat /s
::del *.uvgui.* /s
exit
